codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
			  only_pulls: false
        branches: null
        flags: null
				paths: null

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
  javascript:
    enable_partials: yes

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
