Resources:
  ConfigurationsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      BucketName: ${self:custom.buckets.configurations}
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

# Print out the name of the bucket that is created
Outputs:
  ConfigurationsBucketName:
    Value:
      Ref: ConfigurationsBucket
